# -*- coding: utf-8 -*-
"""
/***************************************************************************
 fodler
                                 A QGIS plugin
 drag file from local to qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-19
        copyright            : (C) 2025 by HMQ
        email                : yogawidars52@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from .auto_added import FileSystemWatcherPlugin

def classFactory(iface):
    return FileSystemWatcherPlugin(iface)
